document.addEventListener('DOMContentLoaded',()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const nav=$('.menu-toggle'),links=$('.nav-links');
nav&&links&&nav.addEventListener('click',()=>{links.classList.toggle('open');nav.setAttribute('aria-expanded',links.classList.contains('open'))});
links&&links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));

/* ---------- Reliable CSS 3D tea-kadai hero: no WebGL/CDN dependency ---------- */
const hero=$('.hero-slider');
if(hero){
  $$('.hero-slide',hero).slice(1).forEach(x=>x.remove());
  const slide=$('.hero-slide',hero),oldImg=$('img',slide);
  if(oldImg)oldImg.remove();
  $$('.slider-arrow,.slider-dots,.slider-dot',hero).forEach(x=>x.remove());
  const e=$('.eyebrow',slide),h=$('h1,h2',slide),p=$('p',slide),a=$('.hero-actions',slide);
  e&&(e.textContent='தமிழ் Tea Kadai • Chennai');
  h&&(h.innerHTML='ஒரு டம்ளர் டீ...<br><span>ஒரு முழு எனர்ஜி.</span>');
  p&&(p.textContent='Hot Tea. Fresh Energy. Local Vibe.');
  a&&(a.innerHTML='<a class="btn btn-primary" href="https://wa.me/919962571464?text=Hi%20Kaapi%20yumm%2C%20I%20would%20like%20to%20order%20tea." target="_blank" rel="noreferrer">Order Tea</a><a class="btn btn-light" href="#menu">View Menu</a>');
  slide.classList.add('tea-hero-slide');
  const stage=document.createElement('div');stage.className='tea-3d-stage';stage.innerHTML=`<div class="tea-scene" aria-hidden="true"><div class="tea-back-wall"></div><div class="tea-counter"></div><div class="tea-shelf shelf-a"></div><div class="tea-shelf shelf-b"></div><div class="tea-jars"><i></i><i></i><i></i><i></i><i></i></div><div class="tea-pot"><b></b></div><div class="tea-stove"><i></i></div><div class="tea-worker"><div class="worker-head"><i class="hair"></i><i class="eye e1"></i><i class="eye e2"></i><i class="nose"></i></div><div class="worker-body"></div><div class="worker-veshti"></div><div class="arm arm-left"><i></i></div><div class="arm arm-right"><i></i></div><div class="tea-pitcher"><i class="pitcher-handle"></i><i class="pitcher-spout"></i></div><div class="tea-stream"></div><div class="tea-tumbler"><i></i></div></div><div class="steam"><i></i><i></i><i></i><i></i><i></i></div></div><div class="tea-loader"><b>☕</b><span>Tea is getting ready...</span><i></i></div><div class="tea-scroll">Scroll to explore ↓</div>`;
  hero.prepend(stage);
  const st=document.createElement('style');st.textContent=`
  .hero-slider{position:relative!important;min-height:700px!important;height:min(780px,calc(100vh - 90px))!important;background:#24130d!important;color:#fffaf3;overflow:hidden!important;perspective:1200px}
  .tea-hero-slide{position:relative!important;inset:auto!important;opacity:1!important;visibility:visible!important;min-height:700px;height:100%;z-index:4!important}
  .tea-hero-slide .hero-slide-overlay{z-index:20;background:linear-gradient(90deg,rgba(18,8,4,.94),rgba(32,14,7,.78) 42%,rgba(32,14,7,.12) 100%)!important;pointer-events:none}
  .tea-hero-slide .hero-slide-content{position:relative;z-index:25;height:100%;padding-right:50%;justify-content:center;pointer-events:auto}
  .tea-hero-slide h1,.tea-hero-slide h2{font-size:clamp(46px,6vw,78px);line-height:1.02;text-shadow:0 8px 35px rgba(0,0,0,.35)}
  .tea-hero-slide h1 span,.tea-hero-slide h2 span{color:var(--gold)}
  .tea-3d-stage{position:absolute;inset:0;z-index:8;overflow:hidden;pointer-events:none}
  .tea-scene{position:absolute;inset:0;transform-style:preserve-3d;animation:sceneFloat 7s ease-in-out infinite;filter:drop-shadow(0 35px 45px rgba(0,0,0,.3))}
  .tea-back-wall{position:absolute;width:100%;height:100%;background:radial-gradient(circle at 75% 42%,rgba(176,92,45,.18),transparent 30%),linear-gradient(135deg,#2b160e,#160b08 70%);opacity:.92}
  .tea-counter{position:absolute;left:45%;right:-5%;bottom:8%;height:22%;background:linear-gradient(180deg,#70432b,#32190f);border-top:5px solid #a56c42;transform:rotateX(58deg) translateZ(20px);box-shadow:0 -20px 40px rgba(0,0,0,.3)}
  .tea-shelf{position:absolute;left:57%;width:35%;height:12px;background:linear-gradient(90deg,#7d4b2e,#d19a63,#7d4b2e);box-shadow:0 8px 15px #0006}.shelf-a{top:25%;transform:rotateY(-8deg)}.shelf-b{top:35%;transform:rotateY(-8deg)}
  .tea-jars{position:absolute;left:61%;top:14%;width:30%;display:flex;gap:2%;transform:translateZ(40px);}.tea-jars i{width:17%;height:72px;border-radius:12px 12px 8px 8px;background:linear-gradient(90deg,#6b4a32,#d2a36f 45%,#5b3826);border:2px solid #d2b28e;box-shadow:0 10px 16px #0008}.tea-jars i:after{content:'';display:block;width:70%;height:8px;margin:8px auto;background:#c9c0a9;border-radius:5px}
  .tea-pot{position:absolute;left:54%;bottom:22%;width:105px;height:120px;border-radius:45% 45% 38% 38%;background:linear-gradient(100deg,#536168,#e2e5e5 42%,#657077 72%,#20272b);border:2px solid #c9d0d1;box-shadow:0 18px 30px #0009;transform:perspective(500px) rotateY(-12deg) translateZ(80px)}.tea-pot b{position:absolute;left:18%;top:-14px;width:64%;height:18px;border-radius:50%;background:#707b80;border:2px solid #cbd1d2}.tea-pot:after{content:'';position:absolute;right:-42px;top:35px;width:55px;height:28px;border:10px solid #6b7478;border-left:0;border-radius:0 35px 35px 0;transform:rotate(-12deg)}
  .tea-stove{position:absolute;left:51%;bottom:19%;width:120px;height:30px;border-radius:10px;background:#202529;box-shadow:0 10px 15px #000}.tea-stove i{position:absolute;left:45px;top:-25px;width:28px;height:34px;background:linear-gradient(#ffe9a1,#ff7a22 55%,transparent);clip-path:polygon(50% 0,75% 38%,100% 55%,68% 100%,30% 75%,0 100%,25% 45%);animation:flame .35s infinite alternate}
  .tea-worker{position:absolute;left:66%;bottom:18%;width:230px;height:450px;transform-style:preserve-3d;transform:rotateY(-8deg) translateZ(90px);animation:workerSway 5s ease-in-out infinite}.worker-body{position:absolute;left:65px;top:125px;width:105px;height:175px;border-radius:35px 35px 18px 18px;background:linear-gradient(100deg,#203e4a,#55747b 48%,#18313b);box-shadow:inset -15px 0 20px #0005}.worker-veshti{position:absolute;left:48px;top:285px;width:140px;height:95px;border-radius:8px 8px 25px 25px;background:linear-gradient(90deg,#b9aa91,#f1e7d5 40%,#c9bba2);transform:skewX(-3deg);box-shadow:0 15px 20px #0006}.worker-head{position:absolute;left:83px;top:35px;width:72px;height:85px;border-radius:48% 48% 45% 45%;background:radial-gradient(circle at 60% 38%,#b96e46,#75402d 75%);box-shadow:inset -10px -8px 15px #0004}.hair{position:absolute;left:-3px;top:-8px;width:78px;height:42px;border-radius:50% 55% 35% 35%;background:#17110f;box-shadow:0 8px 0 #17110f}.eye{position:absolute;top:42px;width:6px;height:6px;background:#160d09;border-radius:50%}.e1{left:20px}.e2{left:48px}.nose{position:absolute;left:35px;top:47px;width:7px;height:17px;background:#874a32;border-radius:50%;transform:rotate(-15deg)}
  .arm{position:absolute;top:145px;width:45px;height:145px;border-radius:24px;background:linear-gradient(90deg,#1f3b45,#547079);transform-origin:top center}.arm i{position:absolute;bottom:-10px;left:9px;width:28px;height:30px;border-radius:50%;background:#895033}.arm-left{left:25px;transform:rotate(30deg)}.arm-right{right:15px;transform:rotate(-42deg)}.arm-right i{transform:translate(6px,0)}
  .tea-pitcher{position:absolute;right:-5px;top:270px;width:48px;height:78px;border-radius:8px 8px 18px 18px;background:linear-gradient(90deg,#667176,#eef0ef 45%,#697277);box-shadow:0 8px 14px #0008;transform:rotate(-30deg);z-index:4}.pitcher-handle{position:absolute;left:-18px;top:16px;width:30px;height:40px;border:7px solid #7b8588;border-right:0;border-radius:25px}.pitcher-spout{position:absolute;right:-34px;top:14px;width:38px;height:12px;background:#b7bec0;transform:rotate(-18deg);clip-path:polygon(0 20%,100% 0,100% 65%,0 100%)}
  .tea-stream{position:absolute;right:10px;top:320px;width:8px;height:145px;background:linear-gradient(90deg,#54210f,#a34d24,#54210f);border-radius:50%;transform:rotate(16deg);transform-origin:top;animation:pour 2.4s ease-in-out infinite;box-shadow:0 0 12px #c06a2a55}
  .tea-tumbler{position:absolute;left:5px;top:335px;width:48px;height:70px;border-radius:6px 6px 14px 14px;background:linear-gradient(90deg,#667176,#f1f3f2 42%,#687176);border:2px solid #d8dcdd;transform:perspective(500px) rotateY(-8deg);box-shadow:0 12px 20px #0008}.tea-tumbler i{position:absolute;left:6px;right:6px;top:6px;height:9px;background:#713217;border-radius:50%}
  .steam{position:absolute;left:67%;bottom:37%;width:130px;height:170px;transform:translateZ(120px)}.steam i{position:absolute;bottom:0;width:18px;height:90px;border-radius:50%;border-left:3px solid #f4dfd355;filter:blur(1px);animation:steam 2.6s ease-in-out infinite}.steam i:nth-child(1){left:15px}.steam i:nth-child(2){left:45px;animation-delay:.5s}.steam i:nth-child(3){left:75px;animation-delay:1s}.steam i:nth-child(4){left:105px;animation-delay:1.5s}.steam i:nth-child(5){left:58px;animation-delay:2s}
  .tea-loader{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:10px;background:#24130d;z-index:30;color:#f4dfcf;transition:opacity .6s,visibility .6s}.tea-loader.hide{opacity:0;visibility:hidden;pointer-events:none}.tea-loader b{font-size:36px;animation:teaBob 1.1s infinite}.tea-loader i{width:54px;height:4px;border-radius:99px;background:#6d351f;overflow:hidden}.tea-loader i:after{content:'';display:block;width:50%;height:100%;background:#dfa16a;animation:teaLoad 1s infinite}.tea-scroll{position:absolute;bottom:22px;left:50%;transform:translateX(-50%);z-index:28;font-size:11px;letter-spacing:.12em;text-transform:uppercase;opacity:.75}
  .tea-3d-reveal{opacity:0;transform:translateY(24px) scale(.98);transition:opacity .8s ease,transform .8s ease}.tea-3d-reveal.in{opacity:1;transform:none}
  @keyframes sceneFloat{50%{transform:translateY(-5px) rotateX(.5deg)}}@keyframes workerSway{50%{transform:rotateY(4deg) translateZ(100px) translateY(-4px)}}@keyframes pour{0%,28%{opacity:0;transform:rotate(16deg) scaleY(.2);transform-origin:top}35%,78%{opacity:1;transform:rotate(16deg) scaleY(1)}85%,100%{opacity:0;transform:rotate(16deg) scaleY(.2)}}@keyframes steam{0%{opacity:0;transform:translateY(20px) scale(.7)}35%{opacity:.6}100%{opacity:0;transform:translateY(-90px) translateX(25px) scale(1.3)}}@keyframes flame{to{transform:scaleY(1.25) translateY(-3px)}}@keyframes teaLoad{to{transform:translateX(220%)}}@keyframes teaBob{50%{transform:translateY(-5px)}}
  @media(max-width:950px){.hero-slider{min-height:650px!important;height:calc(100vh - 82px)!important}.tea-hero-slide{min-height:650px}.tea-hero-slide .hero-slide-content{padding-right:42%}.tea-worker{left:62%;transform:scale(.82) rotateY(-8deg) translateZ(80px)}.tea-scene{transform:scale(.9)}}
  @media(max-width:620px){.hero-slider{min-height:720px!important;height:720px!important}.tea-hero-slide{min-height:720px}.tea-hero-slide .hero-slide-overlay{background:linear-gradient(180deg,rgba(20,9,5,.18),rgba(20,9,5,.72) 52%,rgba(20,9,5,.96))!important}.tea-hero-slide .hero-slide-content{padding:0 7% 52%;justify-content:flex-end}.tea-hero-slide h1,.tea-hero-slide h2{font-size:44px}.tea-3d-stage{inset:0 0 38% 0}.tea-worker{left:51%;bottom:2%;transform:scale(.62) rotateY(-8deg)}.tea-pot,.tea-stove,.tea-jars,.tea-shelf{display:none}.tea-counter{left:25%;bottom:-5%;}.tea-scroll{display:none}}
  @media(prefers-reduced-motion:reduce){.tea-scene,.tea-worker,.tea-stream,.steam i,.tea-stove i{animation:none!important}.tea-loader{display:none!important}}
  `;document.head.appendChild(st);
  setTimeout(()=>$('.tea-loader')?.classList.add('hide'),900);
  const tilt=()=>{$$('.menu-card,.info-card,.feature,.gallery-brand-card,.gallery-grid img,.contact-card').forEach(el=>{el.classList.add('tea-3d-reveal');el.addEventListener('pointermove',ev=>{if(innerWidth<850)return;const r=el.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width-.5,y=(ev.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${(-y*5).toFixed(2)}deg) rotateY(${(x*5).toFixed(2)}deg) translateY(-4px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});const io='IntersectionObserver' in window?new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('in'),{threshold:.12}):null;if(io)$$('.tea-3d-reveal').forEach(x=>io.observe(x))};tilt();
}

/* ---------- Demo Kaapi AI assistant ---------- */
if(!$('#kaapi-ai-launcher')){const b=document.createElement('button');b.id='kaapi-ai-launcher';b.type='button';b.textContent='🤖 Ask Kaapi AI';b.style.cssText='position:fixed;right:24px;bottom:72px;z-index:1000;border:0;border-radius:999px;padding:13px 18px;background:#24130d;color:#fff;box-shadow:0 10px 30px #0003;font-weight:700;cursor:pointer';document.body.appendChild(b);const p=document.createElement('div');p.id='kaapi-ai-panel';p.style.cssText='display:none;position:fixed;right:24px;bottom:125px;width:min(360px,calc(100vw - 32px));z-index:1001;background:#fffaf4;border:1px solid #ead8c8;border-radius:18px;box-shadow:0 18px 50px #0003;padding:18px;color:#2b1a14;font-family:inherit';p.innerHTML='<strong>☕ Kaapi AI</strong><p style="margin:8px 0 12px">Hi! Ask me about menu, timings, location or ordering.</p><div style="display:flex;gap:8px"><input id="kaapi-ai-input" placeholder="Ask something..." style="flex:1;padding:10px;border:1px solid #dbc8b7;border-radius:10px"><button id="kaapi-ai-send" style="padding:10px 13px;border:0;border-radius:10px;background:#b95740;color:white">Send</button></div><div id="kaapi-ai-answer" style="margin-top:12px;font-size:14px"></div>';document.body.appendChild(p);const answer=q=>{q=q.toLowerCase();if(/menu|food|eat|breakfast|snack/.test(q))return'We have filter coffee, idli & vada, dosa, ven pongal, sandwiches, toast and evening snacks. Prices are being confirmed.';if(/hour|open|close|time/.test(q))return'We are open every day from 7:00 AM to 10:00 PM.';if(/where|location|address|map/.test(q))return'Kaapi yumm® is at S Mada St, Thiruvanmiyur, Chennai 600041.';if(/phone|call|whatsapp|order/.test(q))return'Call 09962571464 or use WhatsApp to order/check today’s menu.';if(/tea|coffee|kaapi/.test(q))return'Our hero is ready with the local tea-kadai vibe ☕. For today’s availability, WhatsApp us.';return'Try asking: “What is on the menu?”, “What time are you open?”, or “Where are you located?”'};b.onclick=()=>{p.style.display=p.style.display==='none'?'block':'none';if(p.style.display==='block')$('#kaapi-ai-input')?.focus()};$('#kaapi-ai-send').onclick=()=>{$('#kaapi-ai-answer').textContent=answer($('#kaapi-ai-input').value)};$('#kaapi-ai-input').addEventListener('keydown',e=>{if(e.key==='Enter')$('#kaapi-ai-send').click()})}
});